version: "3"

services:
  server:
    build: .
    tty: true
    volumes:
      - .:/go/src/app
      - ./tmp:/go/src/app/tmp
    working_dir: /go/src/app/cmd/server/
    command: air --tmp_dir "../../../tmp" --build.bin "../../../tmp/main" --build.cmd "go build -o ../../../tmp/main ." --build.args_bin "--port 8080"
    networks:
      cluster:
        ipv4_address: 172.26.249.11

  client:
    build: .
    tty: true
    volumes:
      - .:/go/src/app
    environment:
      - SERVER=172.26.249.11:8080
    working_dir: /go/src/app/cmd/client
    networks:
      cluster:
        ipv4_address: 172.26.249.21

networks:
  cluster:
    ipam:
      driver: default
      config:
        - subnet: 172.26.249.0/24
